# Generated by Django 4.2.6 on 2023-10-15 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_image_userimage_original_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimage',
            name='test',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
