# Generated by Django 4.2.6 on 2023-10-15 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userimage_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userimage',
            old_name='thumbnail_image_200px',
            new_name='thumbnail_px_200',
        ),
        migrations.RenameField(
            model_name='userimage',
            old_name='thumbnail_image_400px',
            new_name='thumbnail_px_400',
        ),
    ]
