# Generated by Django 4.2.6 on 2023-10-16 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_thumbnail_image_200px_userimage_thumbnail_px_200_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='test',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
