# Generated by Django 4.2.6 on 2023-10-16 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimage',
            name='image_extension',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='userimage',
            name='image_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
