# Generated by Django 4.2.6 on 2023-10-18 22:07

import accounts.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userimage_image_extension_userimage_image_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpiringLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_to_expired', models.IntegerField(validators=[accounts.validators.validate_time_to_expired])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expiring_link', to='accounts.userimage')),
            ],
        ),
    ]
