# Generated by Django 4.2.6 on 2023-10-18 22:23

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_expiringlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expiringlink',
            name='time_to_expired',
            field=models.IntegerField(blank=True, null=True, validators=[accounts.validators.validate_time_to_expired]),
        ),
    ]
