# Generated by Django 4.2.6 on 2023-10-23 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_expiringlink_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='account_tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.accounttier'),
        ),
    ]
